% =========================================================================
%  04_consolidate_features.m
%
%  Aggregate every per-patient feature file into a single spreadsheet
%  that the classifier can consume.
%
%  Reads every resultado_total_<group>_paciente_<id>.mat under
%  FEATURES_DIR (generated by 03_extract_patient_features.m) and writes
%  a single .xlsx file with one row per patient. The output spreadsheet
%  has the same column set used to train the cascade classifier.
%
%  If you have clinical data for these patients in a separate spreadsheet
%  (e.g. provided by the hospital), join the two spreadsheets externally
%  before running 05_train_classifier.m.
% =========================================================================

clear; clc; close all;

% --- USER CONFIGURATION ---------------------------------------------------
FEATURES_DIR  = fullfile(pwd, 'data', 'features');                  % input .mat
OUTPUT_XLSX   = fullfile(pwd, 'data', 'features_master.xlsx');      % output xlsx

% Add the source tree to the MATLAB path
addpath(genpath(fullfile(pwd, 'src')));

% --- Run the aggregation -------------------------------------------------
tabla_final = consolidate_features_to_excel(FEATURES_DIR, OUTPUT_XLSX);

fprintf('\nAggregated %d patients into %s\n', height(tabla_final), OUTPUT_XLSX);
